[phases.setup]
nixPkgs = ["nodejs_18", "python311Full"]

[phases.install]
cmds = [
  "cd backend && python3 -m ensurepip --upgrade && python3 -m pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python3 main.py"
