[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "cd backend && python -m pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python main.py"
